# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NapchatAlarms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NapchatAlarms
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'

  target 'NapchatAlarmsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NapchatAlarmsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
